### PR TITLE
Integrate fast api into current database

### PR DESCRIPTION
**Pull request by nwnatale24**
* Added to .gitignore. For backend: Removed unnecessary files, Changed file names.
* Got super basic API endpoints working. Started requirements.txt list for python modules.
* Adding mac explorer file to .gitignore.
* Adding example API call for logging the stored resturants in the DB.
* Updated README.md

### CODE REVIEW

**Review by flashkard — APPROVED** [review]
Looks good!

**Comment by nikvas06** [comment]
Also looks good to me

**Comment by nikvas06** [comment]
Didn't mean to close the request, I was trying to approve it. Reopening it

**Review by nikvas06 — APPROVED** [review]
Looks good!

**Comment by nwnatale24** [comment]
* Adapting API calls for Dan's DB update.
* added Adding sample post with parameters to function and test data

User needs change database password to whatever they set it up with in MySQL.

**Pull request merged**
